### ISSUE TITLE
PMing the Bot errors

### ISSUE THREAD

**Issue by joeShuff** [joeShuff/discord-RPGSteveBot#14]
Error collected from SteveBot
```Traceback (most recent call last):
  File "bot.py", line 67, in on_message
    await process_command(bot, message)
  File "/home/ec2-user/Home/discordbots/SteveBot/commands/CommandManager.py", line 46, in process_command
    guild = str(message.guild.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by joeShuff** [comment]
PM issue

**Comment by joeShuff** [comment]
Ignored all messages in PMs now from [commit](https://github.com/joeShuff/discord-RPGSteveBot/commit/61f0f803bb81124613cbd4856b2964145939e647)
